# 基础配置
server:
  port: 8081
  servlet:
    context-path: /
spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  rabbitmq:
    addresses: localhost:9022
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15000
